const data = [
  {
    title: 'Keto Big Mac Bowl',
    author: 'Joe Bloggs',
    description:
      'In a skillet over medium-high heat brown the ground beef. As it cooks add the worcestershire sauce, garlic powder, salt, and pepper. When it is almost cooked through add the onions and continue cooking until the ground beef is cooked through and the onions are translucent. Drain the grease and set aside. In the same skillet add a small amount of olive oil and the shredded cabbage. Saute until cabbage is slightly softened. Salt and pepper to taste. Divide the cabbage between 4 bowls, top each with a 1/4 portion of the ground beef. Sprinkle each with 1/4 cup of shredded cheese and top with 4 pickle slices each. Pour the special sauce over each bowl and serve.',
    time: '21-30 mins',
    cost: '£5-15',
    nutrition: 'Keto',
    ingredients:
      'Ground beef 500g, Worcestershire sauce 1 tablespoon, Garlic powder 1 teaspoon, Salt 1 teaspoon, Pepper ½ teaspoon, Diced onions 50g, Shredded cheddar cheese 200g, Cabbage thinly shredded 400g, Dill Pickle slices 16',
    image: 'TEXT',
    serves: '4',
    rating: 5,
    rating_entries: 23,
    cloudinary_id: 'none',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660138836/Keto-Big-Mac-Bowl_IG-6-660x660_upxoh9.webp',
  },
  {
    title: 'njil',
    author: 'John Doe',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050221/sandie-clarke-DRs0juEZtsc-unsplash_gy32ui.jpg',
  },
  {
    title: '',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050213/thomas-tucker-MNtag_eXMKw-unsplash_f9bdsg.jpg',
  },
  {
    title: 'FOR YOU STEPHEN',
    author: 'TEXT',
    description: 'TEXT',
    time: 'TEXT',
    cost: 'TEXT',
    nutrition: 'TEXT',
    ingredients: 'TEXT',
    image: 'TEXT',
    serves: 'TEXT',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url:
      'https://res.cloudinary.com/dghgcknlo/image/upload/v1660050205/alena-ganzhela-MONzTP2XxUE-unsplash_mh1epp.jpg',
  },
  {
    title: 'Vegan Big Mac',
    author: 'Sally MacDonald',
    description:
      'Mix all the Vegan Big Mac Sauce ingredients together in a small mixing bowl. Put the burgers in the oven – follow the instructions on the packet. Chop the onion into very small pieces, shred the lettuce & slice the gherkins. With a very sharp knife, carefully cut the burger buns into 3 pieces. Spread the Vegan Big Mac sauce onto the sliced bread rolls. Arrange the lettuce, onions & gherkins in the bread rolls. Two minutes before the burger patties are set to come out of the oven, place the cheese slices on top of them. Take the patties out of the oven & build the burgers.',
    time: '21-30 mins',
    cost: '£5-15',
    nutrition: 'Vegan',
    ingredients:
      'Vegan burgers 8, Vegan cheese 4 slices, Large burger buns 4, Large gherkins 2, Diced white onion 2 tablespoons, Half a baby gem Lettuce',
    image: 'TEXT',
    serves: '4',
    rating: 0,
    rating_entries: 0,
    cloudinary_id: 'qwerty',
    image_url: '',
  },
];
